
import { Button } from "@/components/ui/button";
import { FileText } from "lucide-react";
import jsPDF from 'jspdf';

interface PDFGeneratorProps {
  reading: {
    id: string;
    generated_text: string;
    created_at: string;
  };
  disabled?: boolean;
  onExport?: () => void;
}

const PDFGenerator = ({ reading, disabled, onExport }: PDFGeneratorProps) => {
  const generatePDF = () => {
    onExport?.();
    
    try {
      const pdf = new jsPDF();
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 20;
      const maxWidth = pageWidth - (margin * 2);
      
      // Set up colors matching Mira's theme
      const primaryColor = [139, 69, 193] as const; // Purple
      const textColor = [51, 51, 51] as const; // Dark gray
      const accentColor = [236, 72, 153] as const; // Pink
      
      // Add header with Mira branding
      pdf.setFillColor(139, 69, 193);
      pdf.rect(0, 0, pageWidth, 40, 'F');
      
      // Add Mira title
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(24);
      pdf.text('Mira', margin, 25);
      
      // Add subtitle
      pdf.setFontSize(12);
      pdf.text('Your AI Astral Guide', margin, 35);
      
      // Add reading title
      pdf.setTextColor(textColor[0], textColor[1], textColor[2]);
      pdf.setFontSize(18);
      const readingDate = new Date(reading.created_at).toLocaleDateString();
      pdf.text(`Cosmic Reading - ${readingDate}`, margin, 60);
      
      // Add decorative line
      pdf.setDrawColor(accentColor[0], accentColor[1], accentColor[2]);
      pdf.setLineWidth(2);
      pdf.line(margin, 70, pageWidth - margin, 70);
      
      // Add reading content
      pdf.setTextColor(textColor[0], textColor[1], textColor[2]);
      pdf.setFontSize(11);
      
      // Split text into lines that fit the page width
      const lines = pdf.splitTextToSize(reading.generated_text, maxWidth);
      let yPosition = 85;
      
      lines.forEach((line: string) => {
        if (yPosition > pageHeight - 30) {
          pdf.addPage();
          yPosition = 30;
        }
        pdf.text(line, margin, yPosition);
        yPosition += 6;
      });
      
      // Add footer
      const footerY = pageHeight - 15;
      pdf.setFontSize(8);
      pdf.setTextColor(139, 69, 193);
      pdf.text('Generated by Mira AI - Your Personal Astrology Guide', margin, footerY);
      
      // Save the PDF
      pdf.save(`mira-cosmic-reading-${readingDate}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
    }
  };

  return (
    <Button
      onClick={generatePDF}
      disabled={disabled}
      size="sm"
      className="bg-gradient-to-r from-pink-600 to-purple-600"
    >
      <FileText className="w-4 h-4 mr-1" />
      {disabled ? 'Exporting...' : 'Export PDF'}
    </Button>
  );
};

export default PDFGenerator;
