// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khqhuzmkmoymwrpfnrth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtocWh1em1rbW95bXdycGZucnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzAyNzYsImV4cCI6MjA2NDU0NjI3Nn0.7amktxXaA7Au6MckJN03bDU9rnM4EpE6zPO9MnFQNOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);